from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GMDEditor(object):
    def setupUi(self, GMDEditor):
        GMDEditor.setObjectName("GMDEditor")
        GMDEditor.setEnabled(True)
        GMDEditor.resize(355, 355)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GMDEditor.sizePolicy().hasHeightForWidth())
        GMDEditor.setSizePolicy(sizePolicy)
        GMDEditor.setMinimumSize(QtCore.QSize(355, 355))
        GMDEditor.setMaximumSize(QtCore.QSize(355, 355))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(122, 129, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(122, 129, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 38, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 133, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 63, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 47, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(122, 129, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 43, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(122, 129, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(122, 129, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 38, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 133, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 63, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 47, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(122, 129, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 43, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 133, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(122, 129, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(122, 129, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 38, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 133, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 133, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(126, 133, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 47, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 47, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(220, 220, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(42, 43, 48))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        GMDEditor.setPalette(palette)
        GMDEditor.setMouseTracking(False)
        GMDEditor.setFocusPolicy(QtCore.Qt.ClickFocus)
        GMDEditor.setWindowOpacity(1.0)
        GMDEditor.setLayoutDirection(QtCore.Qt.LeftToRight)
        GMDEditor.setAutoFillBackground(False)
        GMDEditor.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        GMDEditor.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        GMDEditor.setAnimated(True)
        GMDEditor.setDocumentMode(False)
        GMDEditor.setTabShape(QtWidgets.QTabWidget.Rounded)
        GMDEditor.setDockNestingEnabled(False)
        GMDEditor.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        GMDEditor.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(GMDEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(3, 2, 350, 350))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 119, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 122, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 63, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 47, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 70, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 119, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 122, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(60, 63, 69))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 47, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 70, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 122, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 119, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 122, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 122, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(114, 122, 230))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 47, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(46, 47, 52))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Link, brush)
        brush = QtGui.QBrush(QtGui.QColor(66, 70, 77))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tabWidget.setPalette(palette)
        self.tabWidget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tabWidget.setToolTip("")
        self.tabWidget.setToolTipDuration(-1)
        self.tabWidget.setAccessibleDescription("")
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(True)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.main = QtWidgets.QWidget()
        self.main.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.main.setToolTip("")
        self.main.setWhatsThis("")
        self.main.setObjectName("main")
        self.mainLabel = QtWidgets.QLabel(self.main)
        self.mainLabel.setEnabled(True)
        self.mainLabel.setGeometry(QtCore.QRect(0, 0, 100, 20))
        self.mainLabel.setAutoFillBackground(False)
        self.mainLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mainLabel.setTextFormat(QtCore.Qt.AutoText)
        self.mainLabel.setScaledContents(False)
        self.mainLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.mainLabel.setWordWrap(False)
        self.mainLabel.setOpenExternalLinks(False)
        self.mainLabel.setObjectName("mainLabel")
        self.startButton = QtWidgets.QPushButton(self.main)
        self.startButton.setGeometry(QtCore.QRect(260, 290, 80, 26))
        self.startButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.startButton.setCheckable(False)
        self.startButton.setObjectName("startButton")
        self.foldersButton = QtWidgets.QPushButton(self.main)
        self.foldersButton.setGeometry(QtCore.QRect(10, 290, 161, 26))
        self.foldersButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.foldersButton.setCheckable(False)
        self.foldersButton.setObjectName("foldersButton")
        self.audioOutCheck = QtWidgets.QCheckBox(self.main)
        self.audioOutCheck.setGeometry(QtCore.QRect(10, 40, 101, 21))
        self.audioOutCheck.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.audioOutCheck.setCheckable(True)
        self.audioOutCheck.setChecked(True)
        self.audioOutCheck.setTristate(False)
        self.audioOutCheck.setObjectName("audioOutCheck")
        self.videoOutCheck = QtWidgets.QCheckBox(self.main)
        self.videoOutCheck.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.videoOutCheck.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.videoOutCheck.setChecked(True)
        self.videoOutCheck.setObjectName("videoOutCheck")
        self.audioName = QtWidgets.QWidget(self.main)
        self.audioName.setGeometry(QtCore.QRect(10, 80, 221, 31))
        self.audioName.setObjectName("audioName")
        self.audioNameLabel = QtWidgets.QLabel(self.audioName)
        self.audioNameLabel.setGeometry(QtCore.QRect(120, 7, 101, 16))
        self.audioNameLabel.setObjectName("audioNameLabel")
        self.audioNameLine = QtWidgets.QLineEdit(self.audioName)
        self.audioNameLine.setGeometry(QtCore.QRect(0, 5, 113, 22))
        self.audioNameLine.setFrame(True)
        self.audioNameLine.setReadOnly(False)
        self.audioNameLine.setClearButtonEnabled(False)
        self.audioNameLine.setObjectName("audioNameLine")
        self.videoName = QtWidgets.QWidget(self.main)
        self.videoName.setGeometry(QtCore.QRect(10, 110, 221, 31))
        self.videoName.setObjectName("videoName")
        self.videoNameLabel = QtWidgets.QLabel(self.videoName)
        self.videoNameLabel.setGeometry(QtCore.QRect(120, 7, 101, 16))
        self.videoNameLabel.setObjectName("videoNameLabel")
        self.videoNameLine = QtWidgets.QLineEdit(self.videoName)
        self.videoNameLine.setGeometry(QtCore.QRect(0, 5, 113, 22))
        self.videoNameLine.setFrame(True)
        self.videoNameLine.setReadOnly(False)
        self.videoNameLine.setClearButtonEnabled(False)
        self.videoNameLine.setObjectName("videoNameLine")
        self.tabWidget.addTab(self.main, "")
        self.video = QtWidgets.QWidget()
        self.video.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.video.setObjectName("video")
        self.videoLabel = QtWidgets.QLabel(self.video)
        self.videoLabel.setEnabled(True)
        self.videoLabel.setGeometry(QtCore.QRect(0, 0, 111, 20))
        self.videoLabel.setAutoFillBackground(False)
        self.videoLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.videoLabel.setTextFormat(QtCore.Qt.AutoText)
        self.videoLabel.setScaledContents(False)
        self.videoLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.videoLabel.setWordWrap(False)
        self.videoLabel.setOpenExternalLinks(False)
        self.videoLabel.setObjectName("videoLabel")
        self.addTransitionsCheck = QtWidgets.QCheckBox(self.video)
        self.addTransitionsCheck.setGeometry(QtCore.QRect(10, 40, 111, 21))
        self.addTransitionsCheck.setChecked(True)
        self.addTransitionsCheck.setObjectName("addTransitionsCheck")
        self.showcaseSize = QtWidgets.QWidget(self.video)
        self.showcaseSize.setGeometry(QtCore.QRect(10, 140, 180, 30))
        self.showcaseSize.setStatusTip("")
        self.showcaseSize.setWhatsThis("")
        self.showcaseSize.setObjectName("showcaseSize")
        self.showcaseSizeSpin = QtWidgets.QDoubleSpinBox(self.showcaseSize)
        self.showcaseSizeSpin.setGeometry(QtCore.QRect(0, 5, 62, 22))
        self.showcaseSizeSpin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showcaseSizeSpin.setMinimum(1.0)
        self.showcaseSizeSpin.setMaximum(3.0)
        self.showcaseSizeSpin.setSingleStep(0.1)
        self.showcaseSizeSpin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.showcaseSizeSpin.setProperty("value", 1.3)
        self.showcaseSizeSpin.setObjectName("showcaseSizeSpin")
        self.showcaseSizeLabel = QtWidgets.QLabel(self.showcaseSize)
        self.showcaseSizeLabel.setGeometry(QtCore.QRect(65, 7, 91, 16))
        self.showcaseSizeLabel.setObjectName("showcaseSizeLabel")
        self.showcaseSpeed = QtWidgets.QWidget(self.video)
        self.showcaseSpeed.setGeometry(QtCore.QRect(10, 170, 180, 30))
        self.showcaseSpeed.setObjectName("showcaseSpeed")
        self.showcaseSpeedSpin = QtWidgets.QDoubleSpinBox(self.showcaseSpeed)
        self.showcaseSpeedSpin.setGeometry(QtCore.QRect(0, 5, 62, 22))
        self.showcaseSpeedSpin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.showcaseSpeedSpin.setMinimum(0.1)
        self.showcaseSpeedSpin.setMaximum(1.0)
        self.showcaseSpeedSpin.setSingleStep(0.1)
        self.showcaseSpeedSpin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.showcaseSpeedSpin.setProperty("value", 1.0)
        self.showcaseSpeedSpin.setObjectName("showcaseSpeedSpin")
        self.showcaseSpeedLabel = QtWidgets.QLabel(self.showcaseSpeed)
        self.showcaseSpeedLabel.setGeometry(QtCore.QRect(65, 7, 111, 16))
        self.showcaseSpeedLabel.setObjectName("showcaseSpeedLabel")
        self.musicVolume = QtWidgets.QWidget(self.video)
        self.musicVolume.setGeometry(QtCore.QRect(10, 220, 180, 30))
        self.musicVolume.setObjectName("musicVolume")
        self.musicVolumeSpin = QtWidgets.QDoubleSpinBox(self.musicVolume)
        self.musicVolumeSpin.setGeometry(QtCore.QRect(0, 5, 62, 22))
        self.musicVolumeSpin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.musicVolumeSpin.setMinimum(0.0)
        self.musicVolumeSpin.setMaximum(0.5)
        self.musicVolumeSpin.setSingleStep(0.01)
        self.musicVolumeSpin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.musicVolumeSpin.setProperty("value", 0.05)
        self.musicVolumeSpin.setObjectName("musicVolumeSpin")
        self.musicVolumeLabel = QtWidgets.QLabel(self.musicVolume)
        self.musicVolumeLabel.setGeometry(QtCore.QRect(65, 7, 111, 16))
        self.musicVolumeLabel.setObjectName("musicVolumeLabel")
        self.fadeSpeed = QtWidgets.QWidget(self.video)
        self.fadeSpeed.setGeometry(QtCore.QRect(10, 90, 180, 30))
        self.fadeSpeed.setObjectName("fadeSpeed")
        self.fadeSpeedSpin = QtWidgets.QDoubleSpinBox(self.fadeSpeed)
        self.fadeSpeedSpin.setGeometry(QtCore.QRect(0, 5, 62, 22))
        self.fadeSpeedSpin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fadeSpeedSpin.setMinimum(0.0)
        self.fadeSpeedSpin.setMaximum(2.0)
        self.fadeSpeedSpin.setSingleStep(0.1)
        self.fadeSpeedSpin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.fadeSpeedSpin.setProperty("value", 1.0)
        self.fadeSpeedSpin.setObjectName("fadeSpeedSpin")
        self.fadeSpeedLabel = QtWidgets.QLabel(self.fadeSpeed)
        self.fadeSpeedLabel.setGeometry(QtCore.QRect(65, 7, 111, 16))
        self.fadeSpeedLabel.setObjectName("fadeSpeedLabel")
        self.voiceVolume = QtWidgets.QWidget(self.video)
        self.voiceVolume.setGeometry(QtCore.QRect(10, 250, 180, 30))
        self.voiceVolume.setObjectName("voiceVolume")
        self.voiceVolumeSpin = QtWidgets.QDoubleSpinBox(self.voiceVolume)
        self.voiceVolumeSpin.setGeometry(QtCore.QRect(0, 5, 62, 22))
        self.voiceVolumeSpin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.voiceVolumeSpin.setMinimum(0.5)
        self.voiceVolumeSpin.setMaximum(2.0)
        self.voiceVolumeSpin.setSingleStep(0.1)
        self.voiceVolumeSpin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.voiceVolumeSpin.setProperty("value", 0.5)
        self.voiceVolumeSpin.setObjectName("voiceVolumeSpin")
        self.voiceVolumeLabel = QtWidgets.QLabel(self.voiceVolume)
        self.voiceVolumeLabel.setGeometry(QtCore.QRect(65, 7, 111, 16))
        self.voiceVolumeLabel.setObjectName("voiceVolumeLabel")
        self.transitionDuration = QtWidgets.QWidget(self.video)
        self.transitionDuration.setGeometry(QtCore.QRect(10, 60, 180, 30))
        self.transitionDuration.setObjectName("transitionDuration")
        self.transitionDurationSpin = QtWidgets.QDoubleSpinBox(self.transitionDuration)
        self.transitionDurationSpin.setGeometry(QtCore.QRect(0, 5, 62, 22))
        self.transitionDurationSpin.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.transitionDurationSpin.setMinimum(0.5)
        self.transitionDurationSpin.setMaximum(10.0)
        self.transitionDurationSpin.setSingleStep(0.1)
        self.transitionDurationSpin.setStepType(QtWidgets.QAbstractSpinBox.DefaultStepType)
        self.transitionDurationSpin.setProperty("value", 5.0)
        self.transitionDurationSpin.setObjectName("transitionDurationSpin")
        self.transitionDurationLabel = QtWidgets.QLabel(self.transitionDuration)
        self.transitionDurationLabel.setGeometry(QtCore.QRect(65, 7, 121, 16))
        self.transitionDurationLabel.setObjectName("transitionDurationLabel")
        self.line = QtWidgets.QFrame(self.video)
        self.line.setGeometry(QtCore.QRect(0, 120, 501, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.video)
        self.line_2.setGeometry(QtCore.QRect(0, 200, 501, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tabWidget.addTab(self.video, "")
        self.render = QtWidgets.QWidget()
        self.render.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.render.setObjectName("render")
        self.renderLabel = QtWidgets.QLabel(self.render)
        self.renderLabel.setEnabled(True)
        self.renderLabel.setGeometry(QtCore.QRect(0, 0, 121, 20))
        self.renderLabel.setAutoFillBackground(False)
        self.renderLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.renderLabel.setTextFormat(QtCore.Qt.AutoText)
        self.renderLabel.setScaledContents(False)
        self.renderLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.renderLabel.setWordWrap(False)
        self.renderLabel.setOpenExternalLinks(False)
        self.renderLabel.setObjectName("renderLabel")
        self.videoQuality = QtWidgets.QWidget(self.render)
        self.videoQuality.setGeometry(QtCore.QRect(10, 40, 180, 30))
        self.videoQuality.setObjectName("videoQuality")
        self.videoQualityLabel = QtWidgets.QLabel(self.videoQuality)
        self.videoQualityLabel.setGeometry(QtCore.QRect(90, 5, 111, 16))
        self.videoQualityLabel.setObjectName("videoQualityLabel")
        self.videoQualityCombo = QtWidgets.QComboBox(self.videoQuality)
        self.videoQualityCombo.setGeometry(QtCore.QRect(0, 3, 81, 22))
        self.videoQualityCombo.setEditable(True)
        self.videoQualityCombo.setObjectName("videoQualityCombo")
        self.videoQualityCombo.addItem("")
        self.videoQualityCombo.addItem("")
        self.videoQualityCombo.addItem("")
        self.videoQualityCombo.addItem("")
        self.videoQualityCombo.addItem("")
        self.videoQualityCombo.addItem("")
        self.videoQualityCombo.addItem("")
        self.videoFPS = QtWidgets.QWidget(self.render)
        self.videoFPS.setGeometry(QtCore.QRect(10, 70, 201, 30))
        self.videoFPS.setObjectName("videoFPS")
        self.videoFPSLabel = QtWidgets.QLabel(self.videoFPS)
        self.videoFPSLabel.setGeometry(QtCore.QRect(90, 5, 111, 16))
        self.videoFPSLabel.setObjectName("videoFPSLabel")
        self.videoFPSCombo = QtWidgets.QComboBox(self.videoFPS)
        self.videoFPSCombo.setGeometry(QtCore.QRect(0, 3, 81, 22))
        self.videoFPSCombo.setEditable(True)
        self.videoFPSCombo.setObjectName("videoFPSCombo")
        self.videoFPSCombo.addItem("")
        self.videoFPSCombo.addItem("")
        self.videoFPSCombo.addItem("")
        self.tabWidget.addTab(self.render, "")
        GMDEditor.setCentralWidget(self.centralwidget)

        self.retranslateUi(GMDEditor)
        self.tabWidget.setCurrentIndex(0)
        self.videoQualityCombo.setCurrentIndex(5)
        self.videoFPSCombo.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(GMDEditor)

    def retranslateUi(self, GMDEditor):
        _translate = QtCore.QCoreApplication.translate
        GMDEditor.setWindowTitle(_translate("GMDEditor", "GMD Editor"))
        self.mainLabel.setToolTip(_translate("GMDEditor", "<html><head/><body><p><br/></p></body></html>"))
        self.mainLabel.setText(_translate("GMDEditor", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Setup Main</span></p></body></html>"))
        self.startButton.setText(_translate("GMDEditor", "Start"))
        self.foldersButton.setToolTip(_translate("GMDEditor", "<html><head/><body><p>Create 6 <span style=\" font-weight:600;\">folders</span> in which you need to upload your <span style=\" font-weight:600;\">contents</span> for video:</p><p>1. <span style=\" font-weight:600;\">Voice</span> - the most important folder, because the voice acting of the video is stored here. The files must be in <span style=\" font-weight:600;\">\'mp3\' or \'wav\'</span> format, and be <span style=\" font-weight:600;\">00.mp3, 01.mp3, 02.mp3, etc</span>. In this order, they occur, and there will be transitions between records.</p><p>2. <span style=\" font-weight:600;\">Showcases</span> - here, as the name implies, there are showcases in the background. The format is <span style=\" font-weight:600;\">\'mp4\'</span>.</p><p>3. <span style=\" font-weight:600;\">Music</span> - music in the background. The format is <span style=\" font-weight:600;\">\'mp3\' or \'wav\'</span>.</p><p>4. TransitionMusic - music in the transition with a preview. Not required if transition is disabled, format is <span style=\" font-weight:600;\">\'mp3\' or \'wav\'</span>.</p><p>5. TransitionPreview - preview on the transition. Optional if transition is disabled, format is <span style=\" font-weight:600;\">\'png\'</span>.</p></body></html>"))
        self.foldersButton.setText(_translate("GMDEditor", "Setup folders for content"))
        self.audioOutCheck.setToolTip(_translate("GMDEditor", "<html><head/><body><p>Render and <span style=\" font-weight:600;\">output</span> file with <span style=\" font-weight:600;\">audio</span>?</p></body></html>"))
        self.audioOutCheck.setText(_translate("GMDEditor", "Output Audio"))
        self.videoOutCheck.setToolTip(_translate("GMDEditor", "<html><head/><body><p>Render and <span style=\" font-weight:600;\">output</span> file with <span style=\" font-weight:600;\">video</span>?</p></body></html>"))
        self.videoOutCheck.setText(_translate("GMDEditor", "Output Video"))
        self.audioName.setToolTip(_translate("GMDEditor", "<html><head/><body><p>Output <span style=\" font-weight:600;\">audio</span> name.</p></body></html>"))
        self.audioNameLabel.setText(_translate("GMDEditor", "Audio File Name"))
        self.audioNameLine.setText(_translate("GMDEditor", "output_audio"))
        self.videoName.setToolTip(_translate("GMDEditor", "<html><head/><body><p>Output <span style=\" font-weight:600;\">video</span> name.</p></body></html>"))
        self.videoNameLabel.setText(_translate("GMDEditor", "Video File Name"))
        self.videoNameLine.setText(_translate("GMDEditor", "output_video"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main), _translate("GMDEditor", "Main"))
        self.videoLabel.setToolTip(_translate("GMDEditor", "<html><head/><body><p><br/></p></body></html>"))
        self.videoLabel.setText(_translate("GMDEditor", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Setup Video</span></p></body></html>"))
        self.addTransitionsCheck.setToolTip(_translate("GMDEditor", "<html><head/><body><p>Whether to <span style=\" font-weight:600;\">add</span> a <span style=\" font-weight:600;\">transitions</span> with previews between voiceovers.</p></body></html>"))
        self.addTransitionsCheck.setText(_translate("GMDEditor", "Add Transitions"))
        self.showcaseSize.setToolTip(_translate("GMDEditor", "<html><head/><body><p>What will be the <span style=\" font-weight:600;\">size</span> of the <span style=\" font-weight:600;\">showcase</span>. 1 - a video will be fully visible</p></body></html>"))
        self.showcaseSizeLabel.setText(_translate("GMDEditor", "Showcase Size"))
        self.showcaseSpeed.setToolTip(_translate("GMDEditor", "<html><head/><body><p><span style=\" font-weight:600;\">Showcase speed </span>- how fast or slow the showcase will be. Everything is clear here.</p></body></html>"))
        self.showcaseSpeedLabel.setText(_translate("GMDEditor", "Showcase Speed"))
        self.musicVolume.setToolTip(_translate("GMDEditor", "<html><head/><body><p>Background <span style=\" font-weight:600;\">music volume</span>.</p></body></html>"))
        self.musicVolumeLabel.setText(_translate("GMDEditor", "Music Volume"))
        self.fadeSpeed.setToolTip(_translate("GMDEditor", "<html><head/><body><p>The <span style=\" font-weight:600;\">speed</span> of <span style=\" font-weight:600;\">fading</span> / dimming during transitions between showcases and voices.</p></body></html>"))
        self.fadeSpeedLabel.setText(_translate("GMDEditor", "Fade Speed"))
        self.voiceVolume.setToolTip(_translate("GMDEditor", "<html><head/><body><p><span style=\" font-weight:600;\">Volume </span>of the<span style=\" font-weight:600;\"> voice.</span></p></body></html>"))
        self.voiceVolumeLabel.setText(_translate("GMDEditor", "Voice Volume"))
        self.transitionDuration.setToolTip(_translate("GMDEditor", "<html><head/><body><p><span style=\" font-weight:600;\">Duration</span> of the <span style=\" font-weight:600;\">transition</span> with preview (in seconds).</p></body></html>"))
        self.transitionDurationLabel.setText(_translate("GMDEditor", "Transition Duration"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.video), _translate("GMDEditor", "Video"))
        self.renderLabel.setToolTip(_translate("GMDEditor", "<html><head/><body><p><br/></p></body></html>"))
        self.renderLabel.setText(_translate("GMDEditor", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Setup Render</span></p></body></html>"))
        self.videoQuality.setToolTip(_translate("GMDEditor", "<html><head/><body><p>The <span style=\" font-weight:600;\">speed</span> of <span style=\" font-weight:600;\">fading</span> / dimming during transitions between showcases and voices.</p></body></html>"))
        self.videoQualityLabel.setText(_translate("GMDEditor", "Video Quality"))
        self.videoQualityCombo.setItemText(0, _translate("GMDEditor", "144"))
        self.videoQualityCombo.setItemText(1, _translate("GMDEditor", "240"))
        self.videoQualityCombo.setItemText(2, _translate("GMDEditor", "360"))
        self.videoQualityCombo.setItemText(3, _translate("GMDEditor", "480"))
        self.videoQualityCombo.setItemText(4, _translate("GMDEditor", "720"))
        self.videoQualityCombo.setItemText(5, _translate("GMDEditor", "1080"))
        self.videoQualityCombo.setItemText(6, _translate("GMDEditor", "2160"))
        self.videoFPS.setToolTip(_translate("GMDEditor", "<html><head/><body><p>The <span style=\" font-weight:600;\">speed</span> of <span style=\" font-weight:600;\">fading</span> / dimming during transitions between showcases and voices.</p></body></html>"))
        self.videoFPSLabel.setText(_translate("GMDEditor", "Video Frame Rate"))
        self.videoFPSCombo.setItemText(0, _translate("GMDEditor", "30"))
        self.videoFPSCombo.setItemText(1, _translate("GMDEditor", "60"))
        self.videoFPSCombo.setItemText(2, _translate("GMDEditor", "120"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.render), _translate("GMDEditor", "Render"))
